---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: metrics
spec:
  encryptedData:
    admin-password: AgCUDHsYaHqQnsmi+jnH8rRQUlhfTZ3i92RFsXtFS8Kwk+fdWjJUW5pnrU1pYRyNSq9vLLw0lmnP/EFCtjQgugj5YVfVX7TPNZ3YfuvyYfn7eEvty/IjtS5NTmYrm++xQUghHmgeYNRCDVX0wsiK1PPNZpxm1tmHHQuSKS7V+DM9SLY+KlPMuWKRg+szFNfjHPAPo7lPAIG2bTdEc06hNFCbt8WMlYWTs8y85w/bC/eu1WP+ridAtyrGRxozSJmLeeIFkMot0tBL3KBcSVTN1oZq6fUVHqoNuHVAsWJoGlzVJCOk/qIS8RbFbjuwAEoagHWG3DZlth/1EPiZ8duC4vLmu9p48au7fcLPnsiY+PKE+PF6RtcFtsq0qrBeO78ILcfy9jdJb/l7UpClI4dTHs6C8woZs5wTa6o/+S/HGY90A6JPoZTelEDBPlSojdQwqwOJk8s4IJmBhB3UrImiPEzZNPVKPxF6WtLmwBNsRjLqtA7pFKl++1zculTfUsYdroEP5axpk++k0Hgmr1Yl4BZSApt0wBKgU9ibN5KImJ3T5tweASaaPoutdFQbYcGEy1b3nLnOGvtC0Du/wZjHqYBrhaRwCcwP1B2t/uaG+oqJLOYXyxwyTjn60wiVemUr18FwOyRmahNkDGWUPMr7HWuZkJJj1qiUe3qLsiwABYeQZwyN/e3OHlFCQfbZVlUOrhZeHll0jM4EDvhJz+X4kl4GfAKBIQ==
    admin-user: AgCNWiHgbTwmcwQNj1eghwTmkrE2+lA5Ttjc39Oi1/6TC/cjhpvJwZ/XIFDUvxpo20xUd2ZN++TjQLRVa1+fdfTmKMoAV9GvsT6OkHPIjpVqRJBeAornN44KdM62xEXN/IZCy71pK9/1UdgPG2/ktKncZEsyBWRILQstKa+GDHcujyNgU580G4ZLk+jaDqQzMmwBSXBGUllGzfy7zwLDBbU8QmXtCzYPFEE2apsK9FJAK9iM7D0yBZtpxi14UU55GDlwb+Urjd2LxgweDENdTK7Jz3qlK+SeDf59AkHc3V6BYlIAPVGHd9qUbWwgZ4awucIW8wf/9AMtxySaAPIQ/OEvlyavxfiYRbRkX85e4TiP2oKv0MAYyV/2yR7N9UB6qdNrPPKOnRc3s1KeoecSMuJSA6Y808Aygw0p6iNrw/sOShAYWoKvffOXsQZpz//yPt/Mv22NUZdUuFEwDFOSDd+w+8ThLumI3GieXQSuNqblLeJy96Rn7Qgd3jWfSer9spC2iHDQSFIV1XyyKR0EJnh5Z91q8o684Pk1br00VEUw8bkvoWekzUtTmFKK23qDflOIw06IcFQMMLJxxaba32yDI07VhkRZE1y2ldrfNPlFatekhpfEnPaKv9oq17YHU+ntDtQeI/cn3Ao7CUagfL7K6+3qDHBUiKfYdbRpsgrt1bZn9FVG6M9lmRFjtL5Xxk6vabw7RQ==
  template:
    metadata:
      name: grafana-admin
      namespace: metrics
    type: Opaque
