---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-superuser
  namespace: postgres
spec:
  encryptedData:
    password: AgCyfJSpdsSKUR52t1uFzfSI3CtjZsFqxZXbdgu2kxNyuRE47N/5K4R6QYUtsxOjifb3zU6NIz7rJ/g7klPHLD36ZKO8YhSd/JMNrl5eBmA/MGglaUFWTlD4kssyKu7LkqqDK4rZWv8BVqIWiqZ657RRZDaC7wDIpsw/v1ynX8mAO4L4tOfmuSDVlkknSdxrIkbAu1X5mNttLptofx2U87nVpnpahzZk9KZFVQDSwjlBOgT/L+AxB0FxoDWcUgqhT0/nV7eRcPIleOsEoUlryOieq7G9P6jyWQtCpDWOCDOkDDwnGytUYpnMEN2uzlYhcn7xutQiKMhuuQHMTf5zzQdPr9T3mO2XqSMCKsh8MnH2EB2q46Kzr09pREPjxaGZPZxlbRyX0+weP1nIEOmFgQJnz5lScSgINOaxlG51f/b2Su3PF9aYdrVM9zFZhqx8u0bnCix0lL4lViXnqVmbWcdlgZEpmR9RrGA3Dr8y2r0BpeJhtdUXGhuWKjo91sj2lfvknkFh/j2e7PI2YS/l6CCvgEitZwnFzbrtFrrUd9YYUJndOaNef2xdekoIQx1aSDL0575Eg8T3FHivOstbxjUlrv2unWRbd1+2TlIWSvK14x/2qFJhnd033QMQLKUPHkOZ5xb8SRY5MQzyVb93wgClWTFKBorA9b0bwxZqSTT3Ro0NENeTbNiiddIpDz6QFTAwo4JKmzXU7twxl9R69ZpYw0FR+mpOK6a4c+W4hydMCQ==
    username: AgAm12xx4mRaposU5otTQH0oG7k8h8XSxrn50VuOXA+BmRQT7tGUiW/UisTD4RnY3Gjsb1zD1J/vQc0rpi9kYCSBpDOW8yfioSE9aD0st+TtBWbhCgYNHl2xqjsiRMPY0nUuwdH6A+MPWufoU+Y79CidTopVk4pa985//BWw6hps15S+Fe/oxBsO4iaAX3LptgB9QNeEvblkG3A1Np7NiORAL+k77dNq4jOyUyMSoOagMaCUDyqybTsq6GbjV7itFSIgRMfIed10wrYI1v+ByQbL7ynPXCSJBHXyqOrNp8wEFf/lMaBjsJFEdFzIV9HtBZ5q4r7eMML2kyl1QTdKfCADqi7XV/6oqIJhtsxI+8thq1RIe+/PLAghml8YsmBfLsN5oHJXyoMWZZDyqKpXnnsKCRMOmTZy5ur6YQwFKAIh9leza/pvE8on+vj+aPHEYS13xDRv2H7ePctLOZBFDRVQPK+/zKY0ZdLotspL7Z/Gr5eM22qjD0AnxB4dzgc0dboR9ot2G9umte7ZDnrjok6eP40+tCZ5IUj3pB/idanIrlpqgvcUVxo9vnBPSZ7McXYU1PWYXSdJn8ANG0Xr4OyxLU2JRmO9jqKxE2lCaZ+7NCfyODoo61l6WKl5azmGFbCm0xMRQTzAZ0a06dYvZ2dq0bKqJ0yC7KmpkeiMvNUbQkkhJOhT+d7Kylot7EbWT+ebwL/Th8uM2g==
  template:
    metadata:
      name: postgresql-superuser
      namespace: postgres
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-user
  namespace: postgres
spec:
  encryptedData:
    password: AgCuKfLXiedEQxEwRiLA443RGmt0WCb7eHWAsteZSonkXCWus8CU0b8WfQE2/xDCOtEjN/FnJCZykjaN8psSBD40fy/mVBZnoHFeo1Kygh2VPCq9XHhYJB4buVGnp/0SlxljQK+hWggLVPXZlc4ck21QZzevvy8oN5BRC23T4m1n8BqS1SiO7ngq/PNEZxsMfEYHSGqXpcxWmbxx2eEI9hnrfJO03uNyRwXv6HPb3dicFHbApQOkKJF6nLczYSBahmfyQPe4FQRxiQbMWWsTApijEyuLJcCRNbd0BQI5b1FC/xZ4YznzrJ/0HlIweuXfOxoKLtIU3aVfvYE6hQ/vJ/vsi+blOgwjVCX7hVdPKoOpVEpme/isopB+KBxO8MSwY8PX3PfHcucX68qRfvcMYFPNXd7cq5Cz54FfCcOb9V0HX08b6bepJNDPByrRyq0lzVv15QR0MHYOk35RrycZOICf1nLz82g4R4eluYvx2UeAvkSHlJbZnha1cLo45Pc1T3x2SBfdkKEgyDkIg2KW7KRSp+x9urU9eh1qmn1fbKqHOVzLZ7kyg7TLMPyYW52/6ID3I+j08NjUTfKTrffGLJWQ2b+3syiQvCd1EP6ZUoIEV+fcikOx44OvZaiwlWIQuOx6Ki7f+vVMS37rfA23VetzDK+6F7yMb8xos1oCTshFlHYA/EnM+oRpzyUgw1JLsxMSymABuxKFzIO7B6kmhjRtHI05dwHihlAtoJin2efRog==
    username: AgCJEfPMc01Wkw6O94QocI1xka6+i8n953lvRvOjuLtFLcuZzzR5Do+9ulJd7pmBihnd2J9e2EhO57ogN6o0rQOVN3jmSS0jDT24S5rE3nU0YGtagT1oSe0UQxzYYjM4M0rhhqgkwpc5IqwFfCogrOu6ACH1YprYo3FigM+scAYAm1sQOSIs3INfzV7XwExsNIRXTp3XZCuzOAduowqIv2iEcVSdMHIFH354hT/aPAfaJ234Sqb6ZwRJJtwk7EVZ4LDGLrMBEoN5VvBm+TvvlceokTLQhOlNYHF9D0CovyQ7QkV9T0lu9KvJcKoqa50X2zbq9FciLn9IwdQgWvxk30OQUt1Ojb5tlc+KsOlnNB+G+/obpXiOfK9ogR1nU1AcnTJ25D9VNTcFtLxRDNAz7vR4xHjtD9DHNyshfX7xa3ZWL79bKC/XRlN3VIL7e+VNuiU6dH2KwwsTcO//aVx7a27bXdXamRve/rfGzwYKWKHfTvHipJUzVasBcs/qUMQveHCkqwx6AdMNV2aWyYHgQyDqpjALUyCT701aSymz4dk3fcHvqbf3zC4Delg+H8HGVqma4BdCFK12Em5SwsCw8MaH+1hHJHw8Ym06tLaaDUa+/raPT6Hf0hAAXt5I00dJpQYIViH2cRvLuIvdZj6Aq+NihHKoc1BEZfW5wvENE0ImrRyQXSzKDqs7N2bYHGQF+aA+Qs2w4xQzyw==
  template:
    metadata:
      name: windmill-user
      namespace: postgres
    type: kubernetes.io/basic-auth
