# State Layer - Merges node definitions with WireGuard public keys
#
# Simplified architecture:
#   - config.nix: All static configuration including deploy.ip
#   - wireguard.json: WireGuard public keys (generated by keygen)
#
# Usage:
#   state = import ./lib/state.nix { inherit root; };
#   mergedConfig = state.mergeNode "server-01" rawConfig;

{ root }:
let
  # Helper to safely read JSON files
  readJsonFile = path:
    if builtins.pathExists path
    then builtins.fromJSON (builtins.readFile path)
    else { };

  # WireGuard state (public keys)
  wireguardStatePath = root + "/hosts/state/wireguard.json";
  wireguardState = readJsonFile wireguardStatePath;

  # Merge a node's config.nix with WireGuard public key from state
  mergeNode = name: config:
    let
      wgState = wireguardState.${name} or null;
      wgPublicKey =
        if wgState != null && wgState ? public_key && wgState.public_key != null
        then wgState.public_key
        else config.wireguard.publicKey or null;
    in
    config // {
      wireguard = (config.wireguard or { }) // {
        publicKey = wgPublicKey;
      };
    };

in
{
  inherit mergeNode wireguardState;
}
